---
- import_tasks: download.yml

- name: Install Determinate Nix
  command: |-
    {{ nix_installer_path }} install \
      --determinate --no-confirm \
      --diagnostic-endpoint="" \
      {% if ansible_system == "Darwin" %}--nix-build-user-id-base {{ nix_first_build_uid - 1 }}{% endif %}
  become: true

- import_tasks: version.yml
