---
- name: Download pinned Determinate Nix installer
  get_url:
    url:      '{{ nix_installer_url }}'
    dest:     '{{ nix_installer_path }}'
    checksum: '{{ nix_installer_sha | mandatory }}'
    mode:     '0o750'

- name: Install Determinate Nix
  command: |-
    {{ nix_installer_path }} install \
      --determinate --no-confirm \
      --diagnostic-endpoint="" \
      {% if ansible_system == "Darwin" %}--nix-build-user-id-base {{ nix_first_build_uid - 1 }}{% endif %}
  become: true

- import_tasks: version.yml
