---
- name: Load platform dependent tarball info
  include_vars: '{{ ansible_os_family }}/{{ ansible_machine }}.yml'

- name: Run Nix purge script
  when: nix_force_purge | bool
  script: files/purge.sh

- import_tasks: 'version.yml'

- import_tasks: 'install.yml'
  when: nix_current_version is not defined

- include_tasks: '{{ ansible_system | lower }}/upgrade.yml'
  when: nix_current_version != nix_version

- include_tasks: '{{ ansible_system | lower }}/homebrew.yml'
  when: ansible_system == "Darwin"

- import_tasks: 'config.yml'

- include_tasks: '{{ ansible_system | lower }}/cleanup.yml'

- name: Cleanup after installation
  file:
    path: '{{ nix_installer_path }}'
    state: absent
  no_log: true
