---
- name: Check current Nix version
  shell: |
    source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    nix --version
  args:
    executable: '/bin/bash'
  register: nix_current_version_raw
  ignore_errors: true
  become_user: '{{ nix_user }}'

- name: Extract Version from output
  when:
    - not nix_current_version_raw.failed
    - "'Determinate Nix' not in nix_current_version_raw.stdout"
  set_fact:
    nix_is_determinate: false
    nix_current_version: >-
      {{ nix_current_version_raw.stdout
      | split() | last | trim }}

- name: Extract Determinate Nix version
  when:
    - not nix_current_version_raw.failed
    - "'Determinate Nix' in nix_current_version_raw.stdout"
  set_fact:
    nix_is_determinate: true
    nix_current_version: >-
      {{ (nix_current_version_raw.stdout
      | regex_findall('Determinate Nix ([^)]+)'))
      | first | default('') | trim }}
