---
- name: Restart nix-daemon on Linux
  listen: Restart nix-daemon
  service:
    name: 'nix-daemon'
    state: 'restarted'
  when: ansible_os_family == "Debian"

- name: Restart nix-daemon on MacOS
  listen: Restart nix-daemon
  community.general.launchd:
    name: 'systems.determinate.nix-daemon.plist'
    state: 'restarted'
  when: ansible_os_family == "Darwin"

- name: Cleanup after installation
  listen: Cleanup Nix installer
  no_log: true
  file:
    path:  '{{ nix_installer_path }}'
    state: 'absent'
